version: "3.8"

networks:
    fit_me_network:
        driver: bridge
    fit_me_network_no_internet:
        driver: bridge
        internal: true

volumes:
    postgres:
    pgadmin:
    redis_data:
        driver: local

services:
    fit_me_app:
        build: ./
        container_name: fit_me_app
        volumes:
            - ./:/var/www/html:cached
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - fit_me_network
            - fit_me_network_no_internet
        extra_hosts:
            - host.docker.internal:host-gateway

    fit_me_db:
        image: mdillon/postgis:latest
        restart: always
        container_name: fit_me_db
        ports:
            - "10083:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        networks:
            - fit_me_network_no_internet

    fit_me_nginx:
        image: nginx:latest
        container_name: fit_me_nginx
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - fit_me_network
        links:
            - fit_me_app

    fit_me_redis:
        image: redis:latest
        container_name: fit_me_redis
        restart: always
        tty: true
        ports:
            - "6385:6379"
        volumes:
            - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
            - redis_data:/data
        networks:
            - fit_me_network

    fit_me_pgadmin4:
        restart: always
        container_name: fit_me_pgadmin4
        networks:
            - fit_me_network
            - fit_me_network_no_internet
        image: dpage/pgadmin4
        depends_on:
            - fit_me_db
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "5050:5050"
        environment:
            PGADMIN_ROOT_PASSWORD: ${DB_PASSWORD}
            PGADMIN_PASSWORD: ${DB_PASSWORD}
            PGADMIN_PRIMARY_PASSWORD: ${DB_PASSWORD}
            PGADMIN_PRIMARY_USER: ${DB_USERNAME}
            PGADMIN_DEFAULT_EMAIL: admin@training.pl
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 5050
