version: "3.8"

networks:
    training_app_network:
        driver: bridge
    training_app_network_no_internet:
        driver: bridge
        internal: true

volumes:
    postgres:
    pgadmin:
    redis_data:
        driver: local

services:
    training_app:
        build: ./
        container_name: training_app
        volumes:
            - ./:/var/www/html:cached
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - training_app_network
            - training_app_network_no_internet
        extra_hosts:
            - host.docker.internal:host-gateway

    training_app_db:
        image: mdillon/postgis:latest
        restart: always
        container_name: training_app_db
        ports:
            - "10083:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        networks:
            - training_app_network_no_internet

    training_app_nginx:
        image: nginx:latest
        container_name: training_app_nginx
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - training_app_network
        links:
            - training_app

    training_app_redis:
        image: redis:latest
        container_name: training_app_redis
        restart: always
        tty: true
        ports:
            - "6385:6379"
        volumes:
            - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
            - redis_data:/data
        networks:
            - training_app_network

    training_app_pgadmin4:
        restart: always
        container_name: training_app_pgadmin4
        networks:
            - training_app_network
            - training_app_network_no_internet
        image: dpage/pgadmin4
        depends_on:
            - training_app_db
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "5050:5050"
        environment:
            PGADMIN_ROOT_PASSWORD: ${DB_PASSWORD}
            PGADMIN_PASSWORD: ${DB_PASSWORD}
            PGADMIN_PRIMARY_PASSWORD: ${DB_PASSWORD}
            PGADMIN_PRIMARY_USER: ${DB_USERNAME}
            PGADMIN_DEFAULT_EMAIL: admin@training.pl
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 5050
